version: '3.9'
services:
  morpheus:
    build:
      context: .
      dockerfile: Dockerfile
    # command: tail -F anything # Use this for logging if needed
    environment:
      # Display X Server GUI.
      - DISPLAY
      # Fix a bug with QT
      - QT_X11_NO_MITSHM=1
      # Configure Nvidia Docker interface.
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      # Grant display access to X Server.
      - /tmp/.X11-unix:/tmp/.X11-unix
      - "/dev:/dev"
      - .:/root/catkin_ws/src/morpheus
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    privileged: true
    network_mode: host