controller_list:
- name: pos_joint_traj_controller
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: True
  joints: &robot_joints
    - waist
    - shoulder
    - elbow
    - forearm_roll
    - wrist_angle
    - wrist_rotate  
- name: gripper_action_controller
  action_ns: gripper_cmd
  default: True
  type: GripperCommand
  joints: &gripper_joints
    - left_finger

arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - waist
    - shoulder
    - elbow
    - forearm_roll
    - wrist_angle
    - wrist_rotate
  constraints:
    goal_time: 1
    stopped_velocity_tolerance: 0.02

gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - left_finger

hardware_interface:
  loop_hz: 100
  group_name: arm
  gripper_name: gripper
  joint_states_topic: joint_states

groups:
  arm:
    operating_mode: position
    profile_type: velocity
    profile_velocity: 131
    profile_acceleration: 25
    torque_enable: true

singles:
  gripper:
    operating_mode: linear_position
    profile_type: velocity
    profile_velocity: 131
    profile_acceleration: 15
    torque_enable: true