controller_list:
- name: pos_joint_traj_controller
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: True
  joints: &robot_joints
    - waist
    - shoulder
    - elbow
    - forearm_roll
    - wrist_angle
    - wrist_rotate  
- name: gripper_action_controller
  action_ns: gripper_cmd
  default: True
  type: GripperCommand
  joints: &gripper_joints
    - left_finger