A_BOT_LINK_VECTOR:
    [
    'base_link_inertia',
    'shoulder_link',
    'upper_arm_link',
    'forearm_link',
    'wrist_1_link',
    'wrist_2_link',
    'wrist_3_link',
    'tcp_collision_link',
    'd415_mount_link',
    'camera_link',
    'coupler',
    'cable_protector',
    'gripper_body',
    'left_outer_knuckle',
    'left_outer_finger',
    'left_inner_finger',
    'left_inner_finger_pad',
    'left_inner_knuckle',
    'right_outer_knuckle',
    'right_outer_finger',
    'right_inner_finger',
    'right_inner_finger_pad',
    'right_inner_knuckle'
    ]

B_BOT_LINK_VECTOR:
    [
    'base_link_inertia',
    'shoulder_link',
    'upper_arm_link',
    'forearm_link',
    'wrist_1_link',
    'wrist_2_link',
    'wrist_3_link',
    'tcp_collision_link',
    'd415_mount_link',
    'camera_link',
    'coupler',
    'cable_protector',
    'gripper_body',
    'left_outer_knuckle',
    'left_outer_finger',
    'left_inner_finger',
    'left_inner_finger_pad',
    'left_inner_knuckle',
    'right_outer_knuckle',
    'right_outer_finger',
    'right_inner_finger',
    'right_inner_finger_pad',
    'right_inner_knuckle'
    ]

UR5E_LINK_VECTOR:
    [
    'base_link_inertia',
    'shoulder_link',
    'upper_arm_link',
    'forearm_link',
    'wrist_1_link',
    'wrist_2_link',
    'wrist_3_link',
    'tcp_collision_link',
    ]

ROBOTIQ_LINK_VECTOR:
    [
    'd415_mount_link',
    'camera_link',
    'coupler',
    'cable_protector',
    'gripper_body',
    'left_outer_knuckle',
    'left_outer_finger',
    'left_inner_finger',
    'left_inner_finger_pad',
    'left_inner_knuckle',
    'right_outer_knuckle',
    'right_outer_finger',
    'right_inner_finger',
    'right_inner_finger_pad',
    'right_inner_knuckle'
    ]

ONROBOT_LINK_VECTOR:
    [
    'quick_changer',
    'angle_bracket',
    'd415_mount_link',
    'camera_link',
    'coupler',
    'cable_protector',
    'gripper_body',
    'left_outer_knuckle',
    'left_outer_finger',
    'left_inner_finger',
    'left_inner_knuckle',
    'right_outer_knuckle',
    'right_outer_finger',
    'right_inner_finger',
    'right_inner_knuckle'
    ]

ALL_ROBOT_LINK_VECTOR:
    [
    'base_link_inertia',
    'shoulder_link',
    'upper_arm_link',
    'forearm_link',
    'wrist_1_link',
    'wrist_2_link',
    'wrist_3_link',
    'tcp_collision_link',
    'd415_mount_link',
    'camera_link',
    'coupler',
    'cable_protector',
    'gripper_body',
    'left_outer_knuckle',
    'left_outer_finger',
    'left_inner_finger',
    'left_inner_finger_pad',
    'left_inner_knuckle',
    'right_outer_knuckle',
    'right_outer_finger',
    'right_inner_finger',
    'right_inner_finger_pad',
    'right_inner_knuckle',
    'quick_changer',
    'angle_bracket'
    ]